# Generated by Django 3.2.8 on 2021-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forlocal', '0003_alter_shop_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='shop',
            field=models.ManyToManyField(to='forlocal.Owner'),
        ),
    ]
