# Generated by Django 3.2.8 on 2022-03-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forlocal', '0009_rename_shop_smartphone_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='status',
            field=models.CharField(choices=[('available', 'In Stock'), ('not available', 'Out Of Stock')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('dell', 'dell'), ('hp', 'hp'), ('lenovo', 'lenovo'), ('asus', 'asus'), ('avita', 'avita'), ('msi', 'msi'), ('toshiba', 'toshiba'), ('acer', 'acer'), ('apple', 'apple')], max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('os', models.CharField(max_length=100, null=True)),
                ('ram', models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('20GB', '20GB')], max_length=100, null=True)),
                ('rom', models.CharField(choices=[('1 TB HDD', '1 TB HDD'), ('2 GB HDD', '32 GB HDD'), ('4 GB HDD', '64 GB HDD'), ('128 GB SSD', '12 GB SSD'), ('256 GB SSD', '256 GB SSD')], max_length=100, null=True)),
                ('display', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=10, null=True)),
                ('offer', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'In Stock'), ('unavailable', 'Out Of Stock')], max_length=100, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forlocal.owner')),
            ],
        ),
    ]
