# Generated by Django 3.2.8 on 2022-03-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forlocal', '0010_auto_20220319_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sfeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(max_length=100, null=True)),
                ('camera', models.CharField(max_length=100, null=True)),
                ('battery', models.CharField(max_length=100, null=True)),
                ('processor', models.CharField(max_length=100, null=True)),
                ('display', models.CharField(max_length=100, null=True)),
                ('phn', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forlocal.smartphone')),
            ],
        ),
    ]
