# Generated by Django 3.2.8 on 2022-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forlocal', '0011_sfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='core',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='generation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
