# Generated by Django 3.2.8 on 2022-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forlocal', '0014_alter_smartphone_rom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB')], max_length=100, null=True),
        ),
    ]
