# Generated by Django 3.2.8 on 2022-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forlocal', '0015_alter_smartphone_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='brand',
            field=models.CharField(choices=[('realme', 'realme'), ('redmi', 'redmi'), ('samsung', 'samsung'), ('apple', 'apple'), ('one plus', 'one plus'), ('motorola', 'motorola'), ('nokia', 'nokia'), ('honor', 'hobor'), ('asus', 'asus'), ('poco', 'poco'), ('vivo', 'vivo')], max_length=100, null=True),
        ),
    ]
