# Generated by Django 4.0 on 2022-03-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forlocal', '0016_alter_smartphone_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='laptop_pic',
            field=models.ImageField(blank=True, default='aloki1.PNG', null=True, upload_to=''),
        ),
    ]
